-- Initialize Database Provisions
-- Create groups
INSERT INTO nfr_provision_group (provision_group, max, provision_group_text) VALUES (1,99,'pgt');
INSERT INTO nfr_provision_group (provision_group, max, provision_group_text) VALUES (5,99,'pgt');
INSERT INTO nfr_provision_group (provision_group, max, provision_group_text) VALUES (2,99,'pgt');
INSERT INTO nfr_provision_group (provision_group, max, provision_group_text) VALUES (10,99,'pgt');
INSERT INTO nfr_provision_group (provision_group, max, provision_group_text) VALUES (12,99,'pgt');
INSERT INTO nfr_provision_group (provision_group, max, provision_group_text) VALUES (14,99,'pgt');
INSERT INTO nfr_provision_group (provision_group, max, provision_group_text) VALUES (15,99,'pgt');
INSERT INTO nfr_provision_group (provision_group, max, provision_group_text) VALUES (20,99,'pgt');
INSERT INTO nfr_provision_group (provision_group, max, provision_group_text) VALUES (25,99,'pgt');
INSERT INTO nfr_provision_group (provision_group, max, provision_group_text) VALUES (27,99,'pgt');
INSERT INTO nfr_provision_group (provision_group, max, provision_group_text) VALUES (28,99,'pgt');
INSERT INTO nfr_provision_group (provision_group, max, provision_group_text) VALUES (34,99,'pgt');

-- Create variants
INSERT INTO nfr_provision_variant (variant_name) VALUES ('NOTICE OF FINAL REVIEW');
INSERT INTO nfr_provision_variant (variant_name) VALUES ('NOTICE OF FINAL REVIEW (DELAYED)');
INSERT INTO nfr_provision_variant (variant_name) VALUES ('NOTICE OF FINAL REVIEW (NO FEES)');
INSERT INTO nfr_provision_variant (variant_name) VALUES ('NOTICE OF FINAL REVIEW (SURVEY REQUIRED)');
INSERT INTO nfr_provision_variant (variant_name) VALUES ('NOTICE OF FINAL REVIEW (TO OBTAIN SURVEY)');

-- Helper functions for grabbing variant ids, group ids, current variable id, and current provision id.
CREATE OR REPLACE FUNCTION get_current_provision_id() RETURNS INTEGER AS $$
DECLARE
	provision_id INTEGER;
BEGIN
	SELECT max(id) INTO provision_id FROM nfr_provision;
	return provision_id;
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION get_last_provision_variable_id() RETURNS INTEGER AS $$
DECLARE
	provision_variable_id INTEGER;
BEGIN
	SELECT max(id) INTO provision_variable_id FROM nfr_provision_variable;
	return provision_variable_id;
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION get_variant_default() RETURNS INTEGER AS $$
DECLARE
    variant_id INTEGER;
BEGIN
    SELECT id INTO variant_id FROM nfr_provision_variant WHERE variant_name = 'NOTICE OF FINAL REVIEW';
    RETURN variant_id;
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION get_variant_delayed() RETURNS INTEGER AS $$
DECLARE
    variant_id INTEGER;
BEGIN
    SELECT id INTO variant_id FROM nfr_provision_variant WHERE variant_name = 'NOTICE OF FINAL REVIEW (DELAYED)';
    RETURN variant_id;
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION get_variant_nofees() RETURNS INTEGER AS $$
DECLARE
    variant_id INTEGER;
BEGIN
    SELECT id INTO variant_id FROM nfr_provision_variant WHERE variant_name = 'NOTICE OF FINAL REVIEW (NO FEES)';
    RETURN variant_id;
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION get_variant_surveyreq() RETURNS INTEGER AS $$
DECLARE
    variant_id INTEGER;
BEGIN
    SELECT id INTO variant_id FROM nfr_provision_variant WHERE variant_name = 'NOTICE OF FINAL REVIEW (SURVEY REQUIRED)';
    RETURN variant_id;
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION get_variant_toobtain() RETURNS INTEGER AS $$
DECLARE
    variant_id INTEGER;
BEGIN
    SELECT id INTO variant_id FROM nfr_provision_variant WHERE variant_name = 'NOTICE OF FINAL REVIEW (TO OBTAIN SURVEY)';
    RETURN variant_id;
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION get_provision_group_id(p_provision_group INTEGER)
RETURNS INTEGER AS $$
DECLARE
  pg_id INTEGER;
BEGIN
  SELECT id INTO pg_id FROM nfr_provision_group WHERE provision_group = p_provision_group;
  RETURN pg_id;
END;
$$ LANGUAGE plpgsql;

-- Create Provisions and relations to variants
-- Variant 'NOTICE OF FINAL REVIEW'
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(1),'TEMPLATE VARIABLES - NOTICE OF FINAL REVIEW','','DOCUMENT TYPE',true,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_default());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('ATTENTION_LINE','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('CLIENT_FILE_NO','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('DATE_OF_NOTICE','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('DEADLINE_COMPLETION_REQUIREMENTS','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('FACSIMILE_NUMBER','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('NUMBER_OF_COPIES','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('PURPOSE_GENERIC','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('SALUTATION','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('TELEPHONE_NUMBER','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(2),'FEES','','FEES',true,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_default());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('FEE_APPLICATION_AMOUNT','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('FEE_DOCUMENTATION_AMOUNT','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('FEE_OCCUPATIONAL_RENTAL_AMOUNT','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('FEE_OTHER_CREDIT_AMOUNT','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(5),'REPLACEMENT STATEMENT','','OFFER PREAMBLE',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_default());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('REPLACEMENT_TENURE_TYPE','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(5),'LAND DIFFERS FROM STATEMENT','','OFFER PREAMBLE',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_default());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('WHY_LAND_DIFFERS','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(5),'FREE FIELD - PREAMBLE INFORMATION','','OFFER PREAMBLE',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_default());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(15),'OCCUPATIONAL RENT STATEMENT','','OFFER - MONIES - PAYABLE',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_default());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('OCC_RENT_DETAILS','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(20),'DELIVER SECURITY DEPOSIT - NOTICE OF FINAL REVIEW','','OFFER - SECURITY',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_default());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('SECURITY_AMOUNT','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(20),'BLANKET SECURITY STATEMENT','','OFFER - SECURITY',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_default());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('BLANKET_BOND_NAME','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(20),'FREE FIELD FOR SECURITY SECTION','','OFFER - SECURITY',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_default());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(25),'INSURANCE REQUIRED - NOTICE OF FINAL REVIEW - OTHER','','OFFER - INSURANCE',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_default());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(25),'INSURANCE REQUIRED - NOTICE OF FINAL REVIEW - CERTIFICATE REQUIRED','','OFFER - INSURANCE',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_default());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(25),'FREE FIELD FOR INSURANCE','','OFFER - INSURANCE',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_default());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(34),'FREE FIELD - ADDITIONAL REQUIREMENTS','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_default());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(34),'FREE FIELD - ADDITIONAL REQUIREMENTS - 2','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_default());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(34),'ADDITIONAL REQUIREMENTS - MANAGEMENT PLAN','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_default());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(34),'ADDITIONAL REQUIREMENTS - ZONING APPROVAL','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_default());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('LOCAL_GOVERNMENT','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('PURPOSE_GENERIC','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(34),'ADDITIONAL REQUIREMENTS - IMPROVEMENTS STAT DEC','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_default());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(34),'ADDITIONAL REQUIREMENTS - TAX CLEARANCE CERTIFICATE','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_default());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('TAX_COLLECTOR_OFFICE','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(34),'ADDITIONAL REQUIREMENTS - AFFILIATE STATUS CERTIFICATE','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_default());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(34),'ADDITIONAL REQUIREMENTS - OBTAIN AND DELIVER','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_default());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('DEADLINE_TO_DELIVER','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('DOCUMENT_TO_OBTAIN','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(34),'ADDITIONAL REQUIREMENTS - FISHERIES AND OCEANS APPROVAL','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_default());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(34),'ADDITIONAL REQUIREMENTS - COAST GUARD APPROVAL','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_default());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('COAST_GUARD_ADDRESS','',get_current_provision_id());
-- Variant 'NOTICE OF FINAL REVIEW (NO FEES)'
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(1),'TEMPLATE VARIABLES - NOTICE OF FINAL REVIEW - NO FEES','','DOCUMENT TYPE',true,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_nofees());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('ATTENTION_LINE','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('CLIENT_FILE_NO','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('DATE_OF_NOTICE','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('DEADLINE_COMPLETION_REQUIREMENTS','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('FACSIMILE_NUMBER','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('NUMBER_OF_COPIES','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('PURPOSE_GENERIC','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('REPLACEMENT_TENURE_TYPE','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('SALUTATION','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('TELEPHONE_NUMBER','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(5),'REPLACEMENT STATEMENT','','PREAMBLE',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_nofees());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('REPLACEMENT_TENURE_TYPE','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(5),'LAND DIFFERS FROM STATEMENT','','PREAMBLE',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_nofees());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('WHY_LAND_DIFFERS','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(5),'FREE FIELD - PREAMBLE INFORMATION','','PREAMBLE',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_nofees());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(20),'DELIVER SECURITY DEPOSIT - NOTICE OF FINAL REVIEW','','OFFER - SECURITY',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_nofees());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('SECURITY_AMOUNT','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(20),'BLANKET SECURITY STATEMENT','','OFFER - SECURITY',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_nofees());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('BLANKET_BOND_NAME','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(20),'FREE FIELD FOR SECURITY SECTION','','OFFER - SECURITY',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_nofees());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(25),'INSURANCE REQUIRED - NOTICE OF FINAL REVIEW - OTHER','','OFFER - INSURANCE',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_nofees());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(25),'INSURANCE REQUIRED - NOTICE OF FINAL REVIEW - CERTIFICATE REQUIRED','','OFFER - INSURANCE',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_nofees());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(25),'FREE FIELD FOR INSURANCE','','OFFER - INSURANCE',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_nofees());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(34),'FREE FIELD - ADDITIONAL REQUIREMENTS','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_nofees());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(34),'FREE FIELD - ADDITIONAL REQUIREMENTS - 2','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_nofees());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(34),'ADDITIONAL REQUIREMENTS - MANAGEMENT PLAN','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_nofees());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(34),'ADDITIONAL REQUIREMENTS - ZONING APPROVAL','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_nofees());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('LOCAL_GOVERNMENT','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('PURPOSE_GENERIC','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(34),'ADDITIONAL REQUIREMENTS - IMPROVEMENTS STAT DEC','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_nofees());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(34),'ADDITIONAL REQUIREMENTS - TAX CLEARANCE CERTIFICATE','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_nofees());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('TAX_COLLECTOR_OFFICE','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(34),'ADDITIONAL REQUIREMENTS - AFFILIATE STATUS CERTIFICATE','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_nofees());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(34),'ADDITIONAL REQUIREMENTS - OBTAIN AND DELIVER','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_nofees());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('DEADLINE_TO_DELIVER','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('DOCUMENT_TO_OBTAIN','',get_current_provision_id());
-- Variant 'NOTICE OF FINAL REVIEW (DELAYED)'
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(1),'TEMPLATE VARIABLES - NOTICE OF FINAL REVIEW - DELAYED','','DOCUMENT TYPE',true,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_delayed());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('ATTENTION_LINE','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('CLIENT_FILE_NO','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('DATE_OF_NOTICE','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('DEADLINE_COMPLETION_REQUIREMENTS','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('FACSIMILE_NUMBER','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('NUMBER_OF_COPIES','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('PURPOSE_GENERIC','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('SALUTATION','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('TELEPHONE_NUMBER','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('TENURE_TYPE','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(2),'FEES','','FEES',true,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_delayed());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('FEE_APPLICATION_AMOUNT','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('FEE_DOCUMENTATION_AMOUNT','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('FEE_OCCUPATIONAL_RENTAL_AMOUNT','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('FEE_OTHER_CREDIT_AMOUNT','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(5),'REPLACEMENT STATEMENT','','PREAMBLE',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_delayed());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('REPLACEMENT_TENURE_TYPE','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(5),'LAND DIFFERS FROM STATEMENT','','PREAMBLE',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_delayed());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('WHY_LAND_DIFFERS','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(5),'FREE FIELD - PREAMBLE INFORMATION','','PREAMBLE',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_delayed());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(10),'SURVEY CONFIRMATION - CLIENT PAYS - DELAYED','','OFFER SURVEY',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_delayed());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('DEADLINE_COMPLETE_SURVEY','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('DEADLINE_CONFIRM_SURVEY','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('MAXIMUM_AREA','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('RATE_PER_METRE','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(10),'SURVEY DEPOSIT - DELAYED','','OFFER SURVEY',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_delayed());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('SURVEY DEPOSIT - DELAYED','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('DEPOSIT_AMOUNT_SURVEY','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('MAXIMUM_AREA','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('RATE_PER_METRE','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(10),'PREPARE BOUNDARY PLAN (CLIENT PAYS)','','OFFER SURVEY',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_delayed());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(12),'MONIES PAYABLE - NOTICE OF FINAL REVIEW - DELAYED','','OFFER SURVEY',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_delayed());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(12),'ESTIMATED MONIES PAYABLE - NOTICE OF FINAL REVIEW - DELAYED','','OFFER SURVEY',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_delayed());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(15),'OCCUPATIONAL RENT STATEMENT','','OFFER - MONIES - PAYABLE',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_delayed());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('OCC_RENT_DETAILS','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(20),'DELIVER SECURITY DEPOSIT - NOTICE OF FINAL REVIEW','','OFFER - SECURITY',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_delayed());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('SECURITY_AMOUNT','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(20),'DELIVER SECURITY DEPOSIT (& SURVEY DEPOSIT) - NOTICE OF FINAL REVIEW','','OFFER - SECURITY',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_delayed());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(20),'BLANKET SECURITY STATEMENT','','OFFER - SECURITY',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_delayed());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('BLANKET_BOND_NAME','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(20),'FREE FIELD FOR SECURITY SECTION','','OFFER - SECURITY',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_delayed());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(25),'INSURANCE REQUIRED - NOTICE OF FINAL REVIEW - OTHER','','OFFER - INSURANCE',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_delayed());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(25),'INSURANCE REQUIRED - NOTICE OF FINAL REVIEW - CERTIFICATE REQUIRED','','OFFER - INSURANCE',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_delayed());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(25),'FREE FIELD FOR INSURANCE','','OFFER - INSURANCE',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_delayed());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(34),'FREE FIELD - ADDITIONAL REQUIREMENTS','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_delayed());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(34),'ADDITIONAL REQUIREMENTS - MANAGEMENT PLAN','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_delayed());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(34),'ADDITIONAL REQUIREMENTS - ZONING APPROVAL','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_delayed());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('LOCAL_GOVERNMENT','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('PURPOSE_GENERIC','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(34),'ADDITIONAL REQUIREMENTS - IMPROVEMENTS STAT DEC','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_delayed());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(34),'ADDITIONAL REQUIREMENTS - TAX CLEARANCE CERTIFICATE','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_delayed());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('TAX_COLLECTOR_OFFICE','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(34),'ADDITIONAL REQUIREMENTS - AFFILIATE STATUS CERTIFICATE','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_delayed());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(34),'ADDITIONAL REQUIREMENTS - OBTAIN AND DELIVER','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_delayed());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('DEADLINE_TO_DELIVER','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('DOCUMENT_TO_OBTAIN','',get_current_provision_id());
-- Variant 'NOTICE OF FINAL REVIEW (TO OBTAIN SURVEY)'
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(1),'TEMPLATE VARIABLES - NOTICE OF FINAL REVIEW - TO OBTAIN SURVEY','','DOCUMENT TYPE',true,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_toobtain());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('ATTENTION_LINE','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('CLIENT_FILE_NO','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('DATE_OF_NOTICE','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('DEADLINE_COMPLETION_REQUIREMENTS','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('FACSIMILE_NUMBER','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('INTERIM_TENURE_TYPE','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('NUMBER_OF_COPIES','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('PURPOSE_GENERIC','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('SALUTATION','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('TELEPHONE_NUMBER','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(2),'FEES','','FEES',true,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_toobtain());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('FEE_APPLICATION_AMOUNT','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('FEE_DOCUMENTATION_AMOUNT','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('FEE_OCCUPATIONAL_RENTAL_AMOUNT','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('FEE_OTHER_CREDIT_AMOUNT','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(5),'REPLACEMENT STATEMENT','','PREAMBLE',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_toobtain());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('REPLACEMENT_TENURE_TYPE','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(5),'LAND DIFFERS FROM STATEMENT','','PREAMBLE',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_toobtain());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('WHY_LAND_DIFFERS','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(5),'FREE FIELD - PREAMBLE INFORMATION','','PREAMBLE',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_toobtain());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(10),'BOUNDARY SURVEY (WE PAY)','','OFFER PREAMBLE',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_toobtain());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(12),'SURVEY DEPOSIT','','OFFER SURVEY',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_toobtain());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('DEADLINE_SURVEY_DEPOSIT','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('DEPOSIT_AMOUNT_SURVEY','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(14),'LETTER AFFIRMING BC LAND SURVEYOR WAS HIRED','','OFFER - OBTAIN SURVEY',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_toobtain());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('DEADLINE_CONFIRM_SURVEY','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(14),'LETTER AFFIRMING BOUNDARY SURVEY','','OFFER - OBTAIN SURVEY',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_toobtain());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(15),'OCCUPATIONAL RENT STATEMENT','','OFFER - MONIES - PAYABLE',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_toobtain());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('OCC_RENT_DETAILS','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(20),'DELIVER SECURITY DEPOSIT - OS','','OFFER - SECURITY',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_toobtain());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('INTERIM_TENURE_TYPE','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('SECURITY_AMOUNT','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(20),'BLANKET SECURITY STATEMENT - OS','','OFFER - SECURITY',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_toobtain());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('BLANKET_BOND_NAME','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('INTERIM_TENURE_TYPE','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(20),'FREE FIELD FOR SECURITY SECTION','','OFFER - SECURITY',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_toobtain());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(25),'INSURANCE REQUIRED - NOTICE OF FINAL REVIEW - OTHER - OS','','OFFER - INSURANCE',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_toobtain());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(25),'INSURANCE REQUIRED - NOTICE OF FINAL REVIEW - CERTIFICATE REQUIRED','','OFFER - INSURANCE',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_toobtain());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(25),'FREE FIELD FOR INSURANCE','','OFFER - INSURANCE',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_toobtain());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(28),'FREE FIELD - ADDITIONAL REQUIREMENTS','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_toobtain());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(28),'FREE FIELD - ADDITIONAL REQUIREMENTS - 2','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_toobtain());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(28),'ADDITIONAL REQUIREMENTS - MANAGEMENT PLAN','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_toobtain());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(28),'ADDITIONAL REQUIREMENTS - ZONING APPROVAL','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_toobtain());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('LOCAL_GOVERNMENT','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('PURPOSE_GENERIC','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(28),'ADDITIONAL REQUIREMENTS - IMPROVEMENTS STAT DEC','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_toobtain());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(28),'ADDITIONAL REQUIREMENTS - TAX CLEARANCE CERTIFICATE','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_toobtain());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('TAX_COLLECTOR_OFFICE','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(28),'ADDITIONAL REQUIREMENTS - AFFILIATE STATUS CERTIFICATE','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_toobtain());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(28),'ADDITIONAL REQUIREMENTS - OBTAIN AND DELIVER','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_toobtain());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('DEADLINE_TO_DELIVER','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('DOCUMENT_TO_OBTAIN','',get_current_provision_id());
-- Variant 'NOTICE OF FINAL REVIEW (SURVEY REQUIRED)'
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(1),'TEMPLATE VARIABLES - NOTICE OF FINAL REVIEW - SURVEY REQUIRED','','DOCUMENT TYPE',true,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_surveyreq());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('ATTENTION_LINE (Attention:  )','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('CLIENT_FILE_NO','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('DATE_OF_NOTICE (July 23,2022)','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('DAYS_TO_DELIVER_DOCUMENTS','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('DAYS_TO_RETURN_DOCUMENTS','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('DEADLINE_COMPLETION_REQUIREMENTS','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('FACSIMILE_NUMBER','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('MAXIMUM_AREA','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('NUMBER_OF_COPIES','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('PURPOSE_GENERIC','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('RATE_PER_METRE','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('SALUTATION','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('TELEPHONE_NUMBER','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(2),'FEES','','FEES',true,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_surveyreq());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('FEE_APPLICATION_AMOUNT','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('FEE_DOCUMENTATION_AMOUNT','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('FEE_OCCUPATIONAL_RENTAL_AMOUNT','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('FEE_OTHER_CREDIT_AMOUNT','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(5),'REPLACEMENT STATEMENT','','PREAMBLE',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_surveyreq());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('REPLACEMENT_TENURE_TYPE','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(5),'LAND DIFFERS FROM STATEMENT','','PREAMBLE',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_surveyreq());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('WHY_LAND_DIFFERS','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(5),'FREE FIELD - PREAMBLE INFORMATION','','PREAMBLE',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_surveyreq());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(10),'SURVEY - MINISTRY PAYS','','OFFER SURVEY',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_surveyreq());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(10),'SURVEY DEPOSIT - DEL','','OFFER SURVEY',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_surveyreq());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('DEADLINE_SURVEY_DEPOSIT','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('DEPOSIT_AMOUNT_SURVEY','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(10),'SURVEY - CLIENT - PAYS','','OFFER SURVEY',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_surveyreq());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('DEADLINE_COMPLETE_SURVEY','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('DEADLINE_CONFIRM_SURVEY','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(10),'PREPARE BOUNDARY PLAN (CLIENT PAYS)','','OFFER SURVEY',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_surveyreq());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(15),'OCCUPATIONAL RENT STATEMENT','','OFFER - MONIES - PAYABLE',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_surveyreq());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('OCC_RENT_DETAILS','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(20),'DELIVER SECURITY DEPOSIT - NOTICE OF FINAL REVIEW','','OFFER - SECURITY',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_surveyreq());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('SECURITY_AMOUNT','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(20),'DELIVER SECURITY DEPOSIT (& SURVEY DEPOSIT) - NOTICE OF FINAL REVIEW','','OFFER - SECURITY',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_surveyreq());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('SECURITY_AMOUNT','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(20),'BLANKET SECURITY STATEMENT','','OFFER - SECURITY',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_surveyreq());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('BLANKET_BOND_NAME','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(20),'FREE FIELD FOR SECURITY SECTION','','OFFER - SECURITY',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_surveyreq());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(25),'INSURANCE REQUIRED - NOTICE OF FINAL REVIEW - OTHER','','OFFER - INSURANCE',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_surveyreq());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(25),'INSURANCE REQUIRED - NOTICE OF FINAL REVIEW - CERTIFICATE REQUIRED','','OFFER - INSURANCE',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_surveyreq());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(25),'FREE FIELD FOR INSURANCE','','OFFER - INSURANCE',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_surveyreq());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(27),'FREE FIELD - ADDITIONAL REQUIREMENTS','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_surveyreq());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(27),'FREE FIELD - ADDITIONAL REQUIREMENTS - 2','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_surveyreq());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(27),'ADDITIONAL REQUIREMENTS - MANAGEMENT PLAN','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_surveyreq());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(27),'ADDITIONAL REQUIREMENTS - ZONING APPROVAL','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_surveyreq());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('LOCAL_GOVERNMENT','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('PURPOSE_GENERIC','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(27),'ADDITIONAL REQUIREMENTS - IMPROVEMENTS STAT DEC','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_surveyreq());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(27),'ADDITIONAL REQUIREMENTS - TAX CLEARANCE CERTIFICATE','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_surveyreq());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('TAX_COLLECTOR_OFFICE','',get_current_provision_id());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(27),'ADDITIONAL REQUIREMENTS - AFFILIATE STATUS CERTIFICATE','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_surveyreq());
INSERT INTO nfr_provision (type, "provisionGroupId", provision_name, free_text, category, mandatory, active_flag) VALUES ('V',get_provision_group_id(27),'ADDITIONAL REQUIREMENTS - OBTAIN AND DELIVER','','ADDITIONAL REQUIREMENTS',false,true);
INSERT INTO nfr_provision_provision_variant_nfr_provision_variant ("nfrProvisionId", "nfrProvisionVariantId") VALUES (get_current_provision_id(), get_variant_surveyreq());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('DEADLINE_TO_DELIVER','',get_current_provision_id());
INSERT INTO nfr_provision_variable (variable_name, variable_value, "provisionId") VALUES ('DOCUMENT_TO_OBTAIN','',get_current_provision_id());
