module.exports = Object.freeze({
  // Licence Type IDs
  LICENCE_TYPE_ID_HIDE_DEALER: 100,
  LICENCE_TYPE_ID_LIVESTOCK_DEALER: 101,
  LICENCE_TYPE_ID_LIVESTOCK_DEALER_AGENT: 102,
  LICENCE_TYPE_ID_GAME_FARM: 103,
  LICENCE_TYPE_ID_SLAUGHTERHOUSE: 104,
  LICENCE_TYPE_ID_DAIRY_FARM: 105,
  LICENCE_TYPE_ID_DAIRY_TANK_TRUCK: 107,
  LICENCE_TYPE_ID_FUR_FARM: 108,
  LICENCE_TYPE_ID_ARTIFICIAL_INSEMINATION_CENTRE: 109,
  LICENCE_TYPE_ID_AUCTIONEER: 111,
  LICENCE_TYPE_ID_PUBLIC_SALE_YARD_OPERATOR: 112,
  LICENCE_TYPE_ID_APIARY: 113,
  LICENCE_TYPE_ID_VETERINARY_DRUG: 114,
  LICENCE_TYPE_ID_DISPENSER: 115,
  LICENCE_TYPE_ID_YARDMAN: 117,
  LICENCE_TYPE_ID_BULK_TANK_MILK_GRADER: 106,
  LICENCE_TYPE_ID_ARTIFICIAL_INSEMINATION_TECHNICIAN: 110,
  LICENCE_TYPE_ID_MEDICATED_FEED: 116,
  LICENCE_TYPE_ID_PRODUCE_EGG_PRODUCT: 120,
  LICENCE_TYPE_ID_PRODUCER_GRADER: 121,
  LICENCE_TYPE_ID_PURCHASE_INEDIBLE_EGG_PRODUCT: 122,
  LICENCE_TYPE_ID_PURCHASE_LIVE_POULTRY: 123,
  LICENCE_TYPE_ID_PURCHASE_UNGRADED_EGGS: 124,
  LICENCE_TYPE_ID_PURCHASE_REJECT_EGGS: 125,
  LICENCE_TYPE_ID_SELL_REJECT_EGGS: 126,
  LICENCE_TYPE_ID_LIMITED_MEDICATED_FEED: 132,
  LICENCE_TYPE_ID_VETERINARY_LAB: 131,
  LICENCE_TYPE_ID_SELL_INEDIBLE_EGG_PRODUCT: 133,

  // Document Generation Types
  DOCUMENT_TYPE_CERTIFICATE: "CERTIFICATE",
  DOCUMENT_TYPE_ENVELOPE: "ENVELOPE",
  DOCUMENT_TYPE_CARD: "CARD",
  DOCUMENT_TYPE_RENEWAL: "RENEWAL",
  DOCUMENT_TYPE_DAIRY_INFRACTION: "DAIRY_INFRACTION",
  DOCUMENT_TYPE_DAIRY_TANK_RECHECK_NOTICE: "DAIRY_TANK_RECHECK_NOTICE",
  DOCUMENT_TYPE_REPORT: "REPORT",

  // System Roles
  SYSTEM_ROLES: {
    SYSTEM_ADMIN: 1,
    INSPECTOR: 2,
    USER: 3,
    READ_ONLY: 4,
  },

  // Front end page access levels
  ACCESS_LEVEL: {
    CREATE: "CREATE",
    EDIT: "EDIT",
    VIEW: "VIEW",
    NONE: "NONE",
  },

  USER_ACTION_TYPES: {
    SEARCH_VIEW_LICENCES: "SEARCH_VIEW_LICENCES",
    SEARCH_VIEW_SITES: "SEARCH_VIEW_SITES",

    DATA_IMPORTS: "DATA_IMPORTS",
    RUN_REPORTS: "RUN_REPORTS",
    ADMINISTRATION: "ADMINISTRATION",
  },

  DAIRY_TEST_SUBSPECIES: {
    SPC1: "SPC1",
    SCC: "SCC",
    CRY: "CRY",
    FFA: "FFA",
    IH: "IH",
  },

  DAIRY_TEST_THRESHOLD_IDS: {
    WATER: 1, // CRY
    IH: 2,
    SCC: 3,
    IBC: 4, // SCP1
    FFA: 5,
  },

  PREMISES_IMPORT_TYPES: {
    NEW_LICENCE: "NEW_LICENCE",
    NEW_SITE: "NEW_SITE",
    UPDATE: "UPDATE",
    DO_NOT_IMPORT: "DO_NOT_IMPORT",
  },

  // Report types
  // Value must match mal_print_job_output.document_type
  REPORTS: {
    ACTION_REQUIRED: "ACTION_REQUIRED",
    APIARY_INSPECTION: "APIARY_INSPECTION",
    APIARY_PRODUCER_REGION: "APIARY_PRODUCER_REGION",
    APIARY_PRODUCER_CITY: "APIARY_PRODUCER_CITY",
    APIARY_SITE: "APIARY_SITE",
    CLIENT_DETAILS: "VETERINARY_DRUG_DETAILS",
    DAIRY_FARM_DETAIL: "DAIRY_FARM_DETAIL",
    DAIRY_FARM_QUALITY: "DAIRY_FARM_QUALITY",
    DAIRY_FARM_TANK: "DAIRY_FARM_TANK",
    DAIRY_TEST_THRESHOLD: "DAIRY_TEST_THRESHOLD",
    LICENCE_LOCATION: "LICENCE_LOCATION",
    LICENCE_EXPIRY: "LICENCE_EXPIRY",
  },
});
