import { PickType } from "@nestjs/swagger";
import { PrintRequestDetailDto } from "./print_request_detail.dto";

export class CreatePrintRequestDetailDto extends PickType(
  PrintRequestDetailDto,
  [
    "dtid",
    "tenure_file_number",
    "incorporation_number",
    "organization_unit",
    "purpose_name",
    "sub_purpose_name",
    "type_name",
    "sub_type_name",
    "first_name",
    "middle_name",
    "last_name",
    "legal_name",
    "licence_holder_name",
    "inspected_date",
    "email_address",
    "phone_number",
    "contact_agent",
    "contact_company_name",
    "contact_first_name",
    "contact_middle_name",
    "contact_last_name",
    "contact_phone_number",
    "contact_email_address",
    "mailing_address",
    "mailing_address_line_1",
    "mailing_address_line_2",
    "mailing_address_line_3",
    "mailing_city",
    "mailing_province_state_code",
    "mailing_postal_code",
    "mailing_zip",
    "mailing_country_code",
    "mailing_country",
    "location_description",
    "create_userid",
    "tenure",
  ] as const
) {}
