export const rawData = 
{
  '@type': 'DispositionTransactionResource',
  links: [
    {
      '@type': 'RelLink',
      rel: 'self',
      href: 'https://t1api.nrs.gov.bc.ca/ttls-api/v1/dispositionTrans/info/280578',
      method: 'GET'
    }
  ],
  dtid: 280578,
  fileNum: '0260507',
  orgUnit: 'PE - LAND MGMNT - PEACE FIELD OFFICE',
  complexLevel: null,
  purpose: 'AGRICULTURE',
  subPurpose: 'EXTENSIVE',
  subType: 'LEASE - PURCHASE OPTION',
  type: 'LEASE',
  bcgsSheet: null,
  airPhotoNum: null,
  locLand: 'JACKFISH LAKE',
  inspectionDate: null,
  interestParcel: [],
  contactCompanyName: null,
  contactFirstName: null,
  contactMiddleName: null,
  contactLastName: null,
  contactPhoneNumber: null,
  contactEmail: null,
  feePayableType: 'Lease Rental',
  feePayableAmount: 0,
  feePayableAmountGst: 0,
  regOfficeStreet: '100-10003 110th Avenue',
  regOfficeCity: 'Fort St. John',
  regOfficeProv: 'BC',
  regOfficePostalCode: 'V1J6M7',
  gstRate: 5,
  gstExempt: 'U',
  gstExemptArea: 0,
  tenantAddr: [
    {
      '@type': 'TenantAddressResource',
      links: [],
      firstName: 'DEMYA',
      middleName: 'BRYNNLEE',
      lastName: 'ANSLEY',
      legalName: null,
      incorporationNum: null,
      emailAddress: null,
      locationSid: 1,
      ipSid: 20708,
      addrSid: 1,
      addrLine1: 'BOX 2222',
      postalCode: 'V0C1J0',
      city: 'CHETWYND',
      zipCode: null,
      addrLine2: null,
      addrLine3: null,
      countryCd: 'CA',
      regionCd: null,
      country: 'CANADA',
      provAbbr: 'BC',
      stateAbbr: null,
      addrType: 'STREET',
      areaCode: '604',
      phoneNumber: '6323463'
    }
  ]
};

export const testData = {
    dtid: "123",
    tenure_file_number: "321",
    primary_contact_name: "test",
    contact_agent: "Mike",
    organization_unit: "test",
    email_address: "test@test.com",
    phone_number: "(321) 321-3210",
    contact_email_address: "test2@test.com",
    contact_phone_number: "(123) 123-1234",
    incorporation_number: "888",
    inspected_date: "Today",
  };