export const rawData = {
  "@type": "DispositionTransactionResource",
  links: [
    {
      "@type": "RelLink",
      rel: "self",
      href: "https://t1api.nrs.gov.bc.ca/ttls-api/v1/dispositionTrans/info/280578",
      method: "GET",
    },
  ],
  dtid: 280578,
  fileNum: "0260078",
  orgUnit: "PE - LAND MGMNT - PEACE FIELD OFFICE",
  complexLevel: null,
  purpose: "AGRICULTURE",
  subPurpose: "EXTENSIVE",
  subType: "LEASE - PURCHASE OPTION",
  type: "LEASE",
  bcgsSheet: null,
  airPhotoNum: null,
  locLand: "JACKFISH LAKE",
  inspectionDate: null,
  interestParcel: [],
  contactCompanyName: null,
  contactFirstName: null,
  contactMiddleName: null,
  contactLastName: null,
  contactPhoneNumber: null,
  contactEmail: null,
  feePayableType: "Lease Rental",
  feePayableAmount: 0,
  feePayableAmountGst: 0,
  regOfficeStreet: "100-1000 100th Avenue",
  regOfficeCity: "Fort St. John",
  regOfficeProv: "BC",
  regOfficePostalCode: "V1k6M7",
  gstRate: 5,
  gstExempt: "U",
  gstExemptArea: 0,
  tenantAddr: [
    {
      "@type": "TenantAddressResource",
      links: [],
      firstName: "Marcus",
      middleName: "Bee",
      lastName: "Ainsley",
      legalName: null,
      incorporationNum: null,
      emailAddress: null,
      locationSid: 1,
      ipSid: 20708,
      addrSid: 1,
      addrLine1: "BOX 2222",
      postalCode: "V0P1J0",
      city: "CHETWYND",
      zipCode: null,
      addrLine2: null,
      addrLine3: null,
      countryCd: "CA",
      regionCd: null,
      country: "CANADA",
      provAbbr: "BC",
      stateAbbr: null,
      addrType: "STREET",
      areaCode: "604",
      phoneNumber: "1231234",
    },
  ],
};

export const rawData2 = {
  "@type": "DispositionTransactionResource",
  links: [
    {
      "@type": "RelLink",
      rel: "self",
      href: "https://t1api.nrs.gov.bc.ca/ttls-api/v1/dispositionTrans/info/921528",
      method: "GET",
    },
  ],
  dtid: 921528,
  fileNum: "123321",
  orgUnit: "VI - LAND MGMNT - VANCOUVER ISLAND SERVICE REGION",
  complexLevel: null,
  purpose: "RESIDENTIAL",
  subPurpose: "RECREATIONAL RESIDENTIAL",
  subType: "STANDARD LEASE",
  type: "LEASE",
  bcgsSheet: "92G002",
  airPhotoNum: null,
  locLand: "VALDES ISLAND",
  inspectionDate: null,
  interestParcel: [
    {
      "@type": "InterestParcelResource",
      links: [],
      interestParcelId: 946628,
      // this
      legalDescription:
        "Block B, District Lot 333, Valdes Island, Nanaimo District, except thereout a strip of land 5 mietres in parallel width adjoining the natural boundary of the Strait of Georgia, the said strip being designated walkway.",
      areaCalcCode: "ESTM",
      areaCalcDescription: "Estimated",
      areaInHectares: 1.21, // this
      expiryDate: null,
      featureCode: "FL98000100",
      areaInSquareMetres: 11975.4574165739,
      areaLengthInMetres: 609.354597425375,
      wktGeometry:
        "POLYGON ((1174103.89146107 451957.951282485, 1173939.52118829 451749.893782351, 1173970.69262164 451731.043831605, 1174140.86102442 451911.801003698, 1174134.27651286 451916.426554883, 1174119.73433255 451935.11984732, 1174117.10323271 451938.911298538, 1174103.89146107 451957.951282485))",
    },
  ],
  contactCompanyName: null,
  contactFirstName: null,
  contactMiddleName: null,
  contactLastName: null,
  contactPhoneNumber: null,
  contactEmail: null,
  feePayableType: "Lease Rental",
  feePayableAmount: 0,
  feePayableAmountGst: 6850,
  regOfficeStreet: "Suite 132 - 1080 Labieux Road",
  regOfficeCity: "Nanaimo",
  regOfficeProv: "BC",
  regOfficePostalCode: "V7T7J7",
  gstRate: 5,
  gstExempt: "N",
  gstExemptArea: 0.5,
  tenantAddr: [
    {
      "@type": "TenantAddressResource",
      links: [],
      firstName: "ARIA",
      middleName: "ROAL",
      lastName: "VEAUX",
      legalName: null,
      incorporationNum: null,
      emailAddress: null,
      locationSid: 1,
      ipSid: 31365,
      addrSid: 1,
      addrLine1: "777 7777 PRINCESS LANE",
      postalCode: "V6E6R7",
      city: "RICHMOND",
      zipCode: null,
      addrLine2: null,
      addrLine3: null,
      countryCd: "CA",
      regionCd: null,
      country: "CANADA",
      provAbbr: "BC",
      stateAbbr: null,
      addrType: "MAILING",
      areaCode: "604",
      phoneNumber: "9988778",
    },
  ],
};
