apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}
  annotations:
    description: "TICDI"
    tags: "nr-ticdi"
    iconClass: icon-js
labels:
  app: ${NAME}
  app.kubernetes.io/part-of: "${NAME}"
parameters:
  - name: NAME
    description: Module name
    value: nr-ticdi
  - name: SUFFIX
    description: Deployment suffix, e.g. pr-### or prod
    required: true
  - name: NAMESPACE
    description: Namespace to deploy to
    value: c57b8f-dev
  - name: DOMAIN
    value: apps.silver.devops.gov.bc.ca
  - name: CPU_REQUEST
    value: 250m
  - name: MEMORY_REQUEST
    value: 1Gi
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: ${NAME}
      name: ${NAME}
    spec:
      lookupPolicy:
        local: false
      tags:
      - name: pr
        from:
          kind: DockerImage
          name: ghcr.io/bcgov/nr-ticdi:pr
        referencePolicy:
          type: Local
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${NAME}
      name: ${NAME}
    spec:
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        name: ${NAME}
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            name: ${NAME}
        spec:
          containers:
            - image: image-registry.openshift-image-registry.svc:5000/${NAMESPACE}/${NAME}:pr
              imagePullPolicy: Always
              name: ${NAME}
              ports:
                - containerPort: 3000
                  protocol: TCP
              resources:
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
              readinessProbe:
                httpGet:
                  path: /
                  port: 3000
                  scheme: HTTP
                # first probe will fire some time between:
                # initialDelaySeconds and initialDelaySeconds + periodSeconds
                initialDelaySeconds: 30
                periodSeconds: 120
                timeoutSeconds: 1
              livenessProbe:
                successThreshold: 1
                failureThreshold: 3
                httpGet:
                  path: /
                  port: 3000
                  scheme: HTTP
                # first probe will fire some time between:
                # initialDelaySeconds and initialDelaySeconds + periodSeconds
                initialDelaySeconds: 30
                periodSeconds: 120
                timeoutSeconds: 5
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${NAME}
      name: ${NAME}
    spec:
      ports:
        - name: 3000-tcp
          protocol: TCP
          port: 80
          targetPort: 3000
      selector:
        name: ${NAME}
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: ${NAME}
      name: ${NAME}
    spec:
      host: ${NAME}.${DOMAIN}
      port:
        targetPort: 3000-tcp
      to:
        kind: Service
        name: ${NAME}
        weight: 100
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
