kind: Service
apiVersion: v1
metadata:
  name: nr-ticdi-git
  namespace: c57b8f-dev
  uid: 3ba15dbd-6aa5-4fda-9646-454887d3f1da
  resourceVersion: '2945390566'
  creationTimestamp: '2022-03-05T16:44:22Z'
  labels:
    app: nr-ticdi-git
    app.kubernetes.io/component: nr-ticdi-git
    app.kubernetes.io/instance: nr-ticdi-git
    app.kubernetes.io/name: nr-ticdi-git
    app.kubernetes.io/part-of: nr-ticdi-git-app
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 14-ubi7
  annotations:
    app.openshift.io/vcs-ref: openshift
    app.openshift.io/vcs-uri: 'https://github.com/bcgov/nr-ticdi.git'
    openshift.io/generated-by: OpenShiftWebConsole
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2022-03-05T16:44:22Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:app.openshift.io/vcs-ref': {}
            'f:app.openshift.io/vcs-uri': {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/name': {}
            'f:app.kubernetes.io/part-of': {}
            'f:app.openshift.io/runtime': {}
            'f:app.openshift.io/runtime-version': {}
        'f:spec':
          'f:ports':
            .: {}
            'k:{"port":8080,"protocol":"TCP"}':
              .: {}
              'f:name': {}
              'f:port': {}
              'f:protocol': {}
              'f:targetPort': {}
          'f:selector':
            .: {}
            'f:app': {}
            'f:deploymentconfig': {}
          'f:sessionAffinity': {}
          'f:type': {}
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: nr-ticdi-git
    deploymentconfig: nr-ticdi-git
  clusterIP: 10.98.191.94
  clusterIPs:
    - 10.98.191.94
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
status:
  loadBalancer: {}
